[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "elcsoft-library"
version = "0.1.1"
description = "Swagger/OpenAPI 기반 공통 REST API 라이브러리 및 코드 생성기"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "requests>=2.31.0",
]

[project.scripts]
generate-common-api = "codegen.generator:main"

[tool.setuptools]
packages = ["elcsoft", "elcsoft.core", "codegen"]
